apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
  namespace: jenkins 
spec:
  tls:
  - secretName: tls-kubernetes
  rules:
  - host: jenkins.dev1.pcfgcp.pkhamdee.com
    http:
      paths:
      - backend:
          serviceName: jenkins-jenkins-k8s
          servicePort: 8080
